### ISSUE TITLE
split frontend into a different repo

### ISSUE THREAD

**Issue by themandalore** [tellor-io/chorus#13]
keep it cleaner

**Comment by krasi-georgiev** [comment]
I thought about this, and would like to start as a single repo.
I think the frontend  will be small enough that a single repo will be ok.
A single repo will simplify keeping the ABIs up to date and will also simplify testing changes.
For example if we want to change something on the contract can test how the front end will look like right away without switching between different repositories.

If this turns out to cause other issues it will be easy to separate the repos as the frontend is all in a separate folder.

**Comment by themandalore** [comment]
yeah, I think it's fine now, but I say we leave it open to switch when it's live because I know from a best practices stand point, someone wanting to pull in the code and actually use it on the soldity side won't want all the extra baggage to dig through

**Comment by krasi-georgiev** [comment]
Yep I am thinking the same, but I am quite positive we can really keep it in a single folder somplitely separate from the solidity code, if it turns out impossible will definitely split it.
https://github.com/tellor-io/chorus/tree/main/frontend

**Comment by krasi-georgiev** [comment]
lets close for now and when/if needed will revisit
