### ISSUE TITLE
Request Withdraw Fix

### ISSUE THREAD

**Issue by themandalore** [tellor-io/chorus#31]
From a usability perspective:
- I think you could lose tokens if you call requestWithdrawToken multiple times.

add in require (requestDate = 0)
and then make it 0 when they request

**Comment by tallywiesenberg** [comment]
#34 I changed `requestWithdrawToken()` to increment the user's amount they requested to withdraw instead of overwriting it. This should ensure they do not lose funds if they request to withdraw twice before they finally withdraw. The waiting period resets on every call of `requestWithdrawToken()`, and the user must wait to withdraw for a timespan relative to the total they requested to withdraw.

I was concerned that transactions would revert on a user's first request for withdrawal because the struct amount would be undefined.Testing also indicates that incrementing the balance requested to withdraw does not revert if the user has not yet requested withdrawal. This is thanks to uints having a default value of 0 in solidity.
